### ISSUE TITLE
CSS drag "handles"

### ISSUE THREAD

**Issue by curtisshipley** [lucasb-eyer/d3-boundingbox#3]
Thanks for creating this plugin. It looks really easy to use!

In the readme you say you don't create any pseudo elements for drag handles, and suggest that should be done purely in css. How could I show corner blocks/handles using pure css?

**Comment by lucasb-eyer** [comment]
Check out [the example](http://lucasb.eyer.be/lab/d3-boundingbox.html). What I mean is basically adding a border/corner/whatever styling to the concerned element.

**Comment by curtisshipley** [comment]
Thanks Lucas. I saw the example, but I guess what I'm asking is there a CSS only way to just get 4 smaller squares positioned over the corners?

**Comment by lucasb-eyer** [comment]
Good question, I'm no CSS expert but I found [this](https://stackoverflow.com/questions/16050006/css-border-on-corners-only) and [this](https://stackoverflow.com/questions/14387690/css-show-only-corner-border) on SO, which look like that's exactly what you're asking for, right?

**Comment by curtisshipley** [comment]
Your google-fu is much better than mine! I think the border image would work.

**Comment by lucasb-eyer** [comment]
Glad that helps; I'll close the issue for now, but feel free to re-open if necessary.
